sudo: required
env:
  - VERSION=6.0.0
before_install:
  # Install latest version docker engine
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - sudo sysctl -w vm.max_map_count=262144
services:
  - docker

before_script:
  - docker image build --rm --no-cache --tag quay.io/shazchaudhry/docker-metricbeat:${VERSION} .

script:
  - docker network create -d bridge metricbeatSDN
  - docker container run -d --rm --name elasticsearch --network=metricbeatSDN --publish 9200:9200 -e "discovery.type=single-node" -e ELASTIC_PASSWORD=changeme docker.elastic.co/elasticsearch/elasticsearch-platinum:${VERSION}
  - sleep 120
  - docker container run -d --rm --name kibana --network=metricbeatSDN --publish 5601:5601 -e ELASTICSEARCH_URL=http://elasticsearch:9200 -e ELASTICSEARCH_USERNAME=elastic -e ELASTICSEARCH_PASSWORD=changeme docker.elastic.co/kibana/kibana:${VERSION}
  - sleep 120
  - docker container run -d --rm --name metricbeat --volume metricbeat_data:/usr/share/metricbeat/data --volume=/proc:/hostfs/proc:ro --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro --volume=/:/hostfs:ro --volume=/var/run/docker.sock:/var/run/docker.sock --network=host --network=metricbeatSDN quay.io/shazchaudhry/docker-metricbeat:${VERSION}  metricbeat -e -system.hostfs=/hostfs
  - docker network inspect metricbeatSDN
  - docker image ls
  - sleep 120
  - docker container ps -a
  #List all Elasticsearch Indices. One entry sould be for metricbeat
  - curl -u elastic:changeme http://127.0.0.1:9200/_cat/health
  - curl -XGET -u elastic:changeme '127.0.0.1:9200/_cat/indices?v&pretty'
  - curl -XGET -u elastic:changeme '127.0.0.1:9200/metricbeat-*/_search?pretty'

after_script:
  - docker login -u="shazchaudhry" -p=${QUAY_PASSWORD} quay.io
  - docker image push quay.io/shazchaudhry/docker-metricbeat:${VERSION}
