sudo: required
env:
  - VERSION=5.5.0
before_install:
  # Install latest version docker engine
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  # Install latest version of docker-compose
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq python-pip && pip install --upgrade pip
  #- sudo pip install docker-compose
  #- docker-compose version
  # https://www.elastic.co/guide/en/elasticsearch/reference/5.0/vm-max-map-count.html
  - sudo sysctl -w vm.max_map_count=262144
services:
  - docker

before_script:
  - docker image build --rm --no-cache --tag quay.io/shazchaudhry/docker-metricbeat:${VERSION} .

script:
  - docker network create -d bridge metricbeatSDN
  - docker container run -d --rm --name elasticsearch --network=metricbeatSDN --publish 9200:9200 docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
  - sleep 120
  - docker container run -d --rm --name metricbeat --volume metricmeat_data:/usr/share/metricbeat/data  --volume=/proc:/hostfs/proc:ro --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro --volume=/:/hostfs:ro --network=host --network=metricbeatSDN --env HOST=elasticsearch --env PORT=9200 --env PROTOCOL=http --env USERNAME=elastic --env PASSWORD=changeme quay.io/shazchaudhry/docker-metricbeat:${VERSION}
  - docker network inspect metricbeatSDN
  - docker image ls
  - sleep 60
  - docker container ps -a
  #List all Elasticsearch Indices. One entry sould be for metricbeat
  - curl -XGET -u elastic:changeme '127.0.0.1:9200/_cat/indices?v&pretty'
  - curl -XGET -u elastic:changeme '127.0.0.1:9200/metricbeat-*/_search?pretty'

after_script:
  - docker login -u="shazchaudhry" -p=${QUAY_PASSWORD} quay.io
  - docker image push quay.io/shazchaudhry/docker-metricbeat:${VERSION}
  - docker image tag quay.io/shazchaudhry/docker-metricbeat:${VERSION} quay.io/shazchaudhry/docker-metricbeat:latest
  - docker image push quay.io/shazchaudhry/docker-metricbeat:latest
