version: "3.1"

services:

    metricbeat:
        image: quay.io/shazchaudhry/docker-metricbeat
        volumes:
          - metricmeat_data:/var/lib/metricmeat
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - HOST=node1
          - PORT=9200
          - PROTOCOL=http
          - USERNAME=elastic
          - PASSWORD=changeme
        deploy:
            mode: global

volumes:
    metricmeat_data:
