metricbeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  metricsets: ["cpu", "load", "core", "diskio", "filesystem", "fsstat", "memory", "network", "process", "socket"]
  period: 10s
  enabled: true
  processes: ['.*']

  # Configure the metric types that are included by these metricsets.
  cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
  core.metrics: ["percentages"]  # The other available option is ticks.

  # Enable collection of cgroup metrics from processes on Linux.
  process.cgroups.enabled: true

  # Include the cumulative CPU tick values with the process metrics. Defaults to false.
  process.include_cpu_ticks: true

#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "image", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s

#---------------------------- Elasticsearch Module ---------------------------
- module: elasticsearch
  metricsets: ["node", "node_stats"]
  period: 10s
  hosts: ["localhost:9200"]

#-------------------------------- Kafka Module -------------------------------
- module: kafka
  metricsets: ["partition"]
  period: 10s
  hosts: ["localhost:9092"]

#------------------------------- Kibana Module -------------------------------
- module: kibana
  metricsets: ["status"]
  period: 10s
  hosts: ["localhost:5601"]

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  username: "${USERNAME}"
  password: "${PASSWORD}"

#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag.
dashboards.enabled: true
